server:
  port: 9001

spring:
  application:
    name: nacos-cloud-payment-provider
  cloud:
    nacos:
      discovery:
        # 配置nacos地址
        server-addr: localhost:8848
# 暴露服务
management:
  endpoints:
    web:
      exposure:
        include: "*"
