server:
  port: 8006

spring:
  application:
    name: consul-cloud-provider-payment
  # consul 服务注册中心
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # 注册的服务名
        service-name: ${spring.application.name}