server:
  port: 2001
spring:
  application:
    name: cloud-seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: cloud_seata_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?useSSL=false
    username: root
    password: 123456
feign:
  hystrix:
    enabled: true
logging:
  level:
    io:
      seata: info
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml