server:
  port: 3344
spring:
  application:
    name: cloud-config-cneter
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yysimple/springcloud-config-atguigu
          # 搜索目录
          search-paths:
            - springcloud-config
      # 读取什么分支
      label: master
  # rabbitmq的相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

# 暴露bus刷新的端点,跟rabbitmq的刷新有关
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
