server:
  port: 8001

# 服务名称
spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率介于0 到 1之间， 1表示全部采集
      probability: 1
  datasource:
    url: jdbc:mysql://localhost:3306/db_cloud_202001?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false
    username: root
    password: 123456
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  instance:
    # 修改eureka服务的status名称
    instance-id: payment-8001
    # 访问路劲可以显示当前服务的ip地址
    prefer-ip-address: true
    # 客户端向注册中心间隔多久发送一次心跳，默认为30s
    # lease-renewal-interval-in-seconds: 30
    # 客户端在不发送心跳后，注册中心需要等待的时间
    # lease-expiration-duration-in-seconds: 90
  client:
    # 入驻eureka
    register-with-eureka: true
    # 去获取已注册的服务，在集群的时候，每个微服务都需要设置为true，配合ribbon进行负载均衡
    fetch-registry: true
    # 将自己注册进的 eureka服务管理中心 的url
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#Mybatis配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.jxkj.springcloud
